#!/bin/bash
# 🧪 BUILD DEMO ZIP — pre-konfigurovaná demo deploy ZIPka pro Hostinger.
#
# Použití:
#   ./scripts/build-demo.sh [VERSION]
#
# Vytvoří appek-DEMO-vX.Y.Z.zip obsahující:
#   - Kompletní customer aplikaci (api + admin + b2b + demo landing)
#   - api/config.local.php pre-fillnutý s credentials pro demo DB
#   - api/.installed flag (přeskočí install wizard)
#   - demo-seed.sql v rootu pro 1-click import
#   - DEMO_DEPLOY.md s instrukcemi

set -e

VERSION="${1:-2.0.18}"
OUT="appek-DEMO-v${VERSION}.zip"

# ─── Demo DB credentials (Hostinger appek_demo) ────────────────
DB_HOST="localhost"
DB_NAME="u880385154_appek_demo"
DB_USER="u880385154_appek_demo"
DB_PASS="Karkulka55+"

# ─── Licence pro demo (plné balíčky) ───────────────────────────
DEMO_LICENSE_KEY="APPEK-BED9-RG9D-MRV8-AAA9-8FBC"
DEMO_ADMIN_EMAIL="demo@appek.cz"
DEMO_ADMIN_PASSWORD="demo1234"

echo "📦 Building DEMO ZIP v${VERSION}"
echo "   DB: ${DB_NAME}@${DB_HOST}"
echo ""

# Smaž starý
rm -f "$OUT"
rm -rf /tmp/appek-demo-build
mkdir -p /tmp/appek-demo-build

# Kopíruj customer-relevant soubory (nikoli vendor/sales)
echo "📋 Kopírování customer souborů…"
for p in api admin b2b demo install.php instalace.html .htaccess robots.txt; do
  if [[ -e "$p" ]]; then
    mkdir -p "/tmp/appek-demo-build/$(dirname "$p")"
    cp -R "$p" "/tmp/appek-demo-build/$(dirname "$p")/" 2>/dev/null || true
  fi
done

# Smaž vendor / config / instalátorové artefakty co se neměly kopírovat
rm -rf /tmp/appek-demo-build/vendor 2>/dev/null
rm -f /tmp/appek-demo-build/api/.installed 2>/dev/null
rm -f /tmp/appek-demo-build/api/config.local.php 2>/dev/null
rm -rf /tmp/appek-demo-build/.git 2>/dev/null

# ─── PRE-CONFIGURED FILES ─────────────────────────────────────────

# 1. api/config.local.php — demo DB credentials + demo flags
echo "🔧 Generuji api/config.local.php…"
cat > /tmp/appek-demo-build/api/config.local.php <<EOF
<?php
/**
 * 🧪 DEMO CONFIG — auto-generated by build-demo.sh
 *
 * Pro demo.appek.cz na Hostinger.
 */

// ─── Hostinger MySQL DB ─────────────────────────────────────────
define('DB_HOST', '${DB_HOST}');
define('DB_NAME', '${DB_NAME}');
define('DB_USER', '${DB_USER}');
define('DB_PASS', '${DB_PASS}');

// ─── License — demo má plný balíček (core + cukrarna + lahudky + ...) ──
define('APP_LICENSE_KEY', '${DEMO_LICENSE_KEY}');

// ─── DEMO REŽIM ─────────────────────────────────────────────────
// Aktivuje:
//   - Auto-login banner v admin/ (api/demo_status.php hlásí demo:true)
//   - 15-min idle timeout (JS-side enforced)
//   - /api/admin_reset_demo.php endpoint pro hodinový reset
define('APPEK_DEMO_MODE', true);
define('APPEK_DEMO_EMAIL', '${DEMO_ADMIN_EMAIL}');
define('APPEK_DEMO_PASSWORD', '${DEMO_ADMIN_PASSWORD}');
define('APPEK_DEMO_SESSION_TTL', 900); // 15 minut

// Session timeout enforced v PHP
ini_set('session.gc_maxlifetime', '900');
ini_set('session.cookie_lifetime', '900');
EOF

# 2. api/.installed flag (přeskočí install wizard)
echo "🏁 Vytvářím api/.installed flag…"
echo "$(date +%Y-%m-%d) — Demo deployment v${VERSION}" > /tmp/appek-demo-build/api/.installed

# 3. demo-seed.sql v rootu pro snadný 1-click import
echo "🌱 Kopíruji demo-seed.sql do rootu…"
if [[ -f deploy/demo-seed.sql ]]; then
  cp deploy/demo-seed.sql /tmp/appek-demo-build/demo-seed.sql
fi

# 4. DEMO_DEPLOY.md — instrukce
cat > /tmp/appek-demo-build/DEMO_DEPLOY.md <<EOF
# 🧪 APPEK DEMO — Deploy na Hostinger

**Cíl:** Plnohodnotné demo na demo.appek.cz s daty, 15-min logoutem a hodinovým resetem.

---

## ✅ Co je už předkonfigurované v ZIPu

- ✅ \`api/config.local.php\` má credentials pro DB \`${DB_NAME}\`
- ✅ Pre-fillnutá licence pro plné balíčky
- ✅ \`APPEK_DEMO_MODE = true\` (auto-login + 15min timeout)
- ✅ \`api/.installed\` flag (přeskočí install wizard)
- ✅ \`demo-seed.sql\` v rootu pro 1-click import dat

---

## 📋 Step-by-step deploy (10 minut práce)

### 1️⃣ Subdomain v Hostinger (pokud ještě neexistuje)
- Hostinger panel → **Subdomains** → Create
- Subdomain: \`demo\`
- Domain: \`appek.cz\`
- Public path: \`public_html/demo\`

### 2️⃣ Upload obsahu ZIPu
Přes Hostinger **File Manager** (nebo FTP/SFTP):
- Otevři \`public_html/demo/\`
- Smaž vše uvnitř (pokud něco zbylo z předchozích testů)
- **Rozbal tuhle ZIPku přímo do \`public_html/demo/\`**

Po uploadu by struktura měla být:
\`\`\`
public_html/demo/
├── api/
│   ├── config.local.php   ← pre-fillnuto
│   ├── .installed          ← flag
│   └── ...
├── admin/
├── b2b/
├── demo/                   ← landing page
├── install.php
├── demo-seed.sql           ← pro import
├── .htaccess
└── DEMO_DEPLOY.md
\`\`\`

### 3️⃣ Import demo dat
1. Hostinger panel → **Databases → phpMyAdmin**
2. Vyber DB \`${DB_NAME}\`
3. Klik **Import** v horním menu
4. Vyber soubor: nahraj z disku \`demo-seed.sql\` (stáhneš z public_html/demo/) nebo dej "Browse" a najdi
5. Klik **Go**

> **Pokud import selže** s "Unknown table" chybou:
> 1. Otevři nejdřív \`https://demo.appek.cz/admin/\` v prohlížeči — to spustí auto-init tabulek
> 2. Pak vrať se na phpMyAdmin a importuj seed znovu

### 4️⃣ Test
Otevři **https://demo.appek.cz/**

Co bys měl vidět:
- 🧪 Landing page s tlačítkem **„Vstoupit do demo"**
- Po kliku → \`demo.appek.cz/admin/\` → **auto-přihlášení**
- Banner: **„🧪 Demo režim — přihlašovací údaje předvyplněny. Session 15 min."**
- V adminu uvidíš: ~30 objednávek, 50 produktů, 12 odběratelů, HACCP logy, šarže

### 5️⃣ Hourly auto-reset (volitelné, doporučené)

Hostinger panel → **Advanced → Cron Jobs** → Add new:
\`\`\`
Příkaz:    /usr/bin/php /home/u880385154/public_html/demo/api/admin_reset_demo.php
Frekvence: 0 * * * *  (každou hodinu v xx:00)
\`\`\`

Tím se každou hodinu data resetují zpět do výchozího stavu — perfektní pro showcase.

---

## 🔒 Bezpečnost

| | |
|---|---|
| DB | \`${DB_NAME}\` (separátní od produkce) |
| 15-min idle timeout | enforced v PHP + JS na frontendu |
| Auto-reset | hodinový (přes cron) |
| noindex | Google nezaindexuje |
| Veřejný login | záměrně — zákazník zkouší APPEK bez registrace |

---

## 🧪 Credentials (jen info — auto-fill funguje sám)

| | |
|---|---|
| URL | https://demo.appek.cz/admin/ |
| E-mail | \`${DEMO_ADMIN_EMAIL}\` |
| Heslo | \`${DEMO_ADMIN_PASSWORD}\` |
| Session TTL | 900 s (15 min) |
| Reset | hodinový (xx:00) |

---

## 🔧 Změna credentials později

Edituj přes Hostinger File Manager:
\`public_html/demo/api/config.local.php\`

Nebo zakázat demo režim:
- Změň \`APPEK_DEMO_MODE\` na \`false\`
- Banner zmizí, login je manuální
EOF

# ─── Build ZIP ────────────────────────────────────────────────────
echo "📦 Tvořím ZIP…"
cd /tmp/appek-demo-build
zip -qr "/tmp/$OUT" .
cd - >/dev/null
mv "/tmp/$OUT" .

# Auto-copy na plochu
DESKTOP="$HOME/Desktop"
if [[ -d "$DESKTOP" ]]; then
  cp "$OUT" "$DESKTOP/"
fi

# Cleanup
rm -rf /tmp/appek-demo-build

SIZE=$(ls -lh "$OUT" | awk '{print $5}')
COUNT=$(unzip -l "$OUT" | tail -1 | awk '{print $2}')

echo ""
echo "═══════════════════════════════════════════════"
echo "✅ DEMO ZIP HOTOVÝ — v${VERSION}"
echo "═══════════════════════════════════════════════"
echo ""
echo "📤 Soubor:   ${OUT}"
echo "📏 Velikost: $SIZE"
echo "📁 Souborů:  $COUNT"
echo "📥 Plocha:   ~/Desktop/${OUT}"
echo ""
echo "🔧 Pre-konfigurováno:"
echo "   ✓ DB: ${DB_NAME}@${DB_HOST}"
echo "   ✓ User: ${DB_USER}"
echo "   ✓ Demo licence + APPEK_DEMO_MODE = true"
echo "   ✓ .installed flag (přeskočí install.php)"
echo "   ✓ demo-seed.sql v rootu k importu"
echo "   ✓ 15-min session TTL"
echo ""
echo "📖 Návod uvnitř ZIPu: DEMO_DEPLOY.md"
